
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

import type { FirebaseOptions } from 'firebase/app';

// Your web app's Firebase configuration
const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyCz2C2J3narD7Jmqi5Xpj16dYNzUGuI_2k",
  authDomain: "inventory-956da.firebaseapp.com",
  projectId: "inventory-956da",
  storageBucket: "inventory-956da.appspot.com",
  messagingSenderId: "764174985892",
  appId: "1:764174985892:web:9519f3157a072703dd1431",
  measurementId: "G-N8EMT26EYD"
};

export function getFirebaseConfig(): FirebaseOptions {
  if (!firebaseConfig || !firebaseConfig.apiKey) {
    throw new Error('No Firebase configuration object provided.' + '\n' +
      'Add your web app\'s configuration object to src/firebase/config.ts');
  }
  return firebaseConfig;
}
